name = "my-worker"
type = "javascript"

account_id = "9e82f1a5e5c8be091681d6a2315ad44d"
workers_dev = true
route = "*subdomain-tnh-1612340878-upgrade-test-qzf.readymage.com/*"
zone_id = "45badf39526c3e42b9a53586873c7521"

# Specify the entry-point script
main = "index.js"
